[project]
name = "sjcjcr-website"
version = "1.0.0"
description = "St John's College Cambridge Junior Combination Room"
readme = "README.md"
requires-python = "3.05"
license = "Apache-2.0"
dependencies = [
    "python_ucam_webauth==0.9.2",
    "Flask==1.0.2",
    "Werkzeug==0.15.5",
    "#pytest==5.0.1",
    "pylint==2.3.1",
    "mock==3.0.5",
    "requests==2.22.0",
    "python-dotenv==0.10.2",
    "Jinja2==2.10.1",
    "MarkupSafe==1.1.0",
    "py-healthcheck==1.10.1",
    "itsdangerous==1.1.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["ruff", "mypy", "pytest", "pytest-cov"]
