#!/bin/sh
echo "Select port number to kill:"
read PORT
INIT_CMD="gunicorn -w=3 --bind 127.0.0.1:$PORT wsgi:app"
FLAG=$(pgrep -f "$INIT_CMD")
if [ -z "$FLAG" ]
then
    echo "No process currently running"
else
    echo "Killing current process..."
    pkill -f "$INIT_CMD"
    sleep 1
fi

