#!/bin/sh
INIT_CMD="gunicorn --bind 127.0.0.1:$PORT wsgi:app"
FLAG=$(pgrep -f "$INIT_CMD")
if [ -z "$FLAG" ]
then
    echo "Starting gunicorn server on port $PORT..."
    $INIT_CMD &
else
    echo "Server already running on port $PORT"
fi

